### ISSUE TITLE
求解答QAQ

### ISSUE THREAD

**Issue by chaochao825** [ZillaRU/ImageSpeaking#1]
本人想做一些硬件加速的工作，请问有更多的模型信息么，bmodel可否分享，
以及求问bert模型在转bmodel过程中算子是否都支持，SWIN操作是经过了优化吗？
另外注意到模型endoer部分为FP32，其余为FP16，转为bmodel后这样的混合精度，转模型过程是否会有问题？运行是否支持？

**Comment by ZillaRU** [comment]
整体流程是很多个bmodel串起来，单个bmodel不存在混精度。bmodel放在压缩包了，readme里面有下载方式。
